(custom-set-variables
 '(neo-theme (quote classic))
 '(neo-smart-open t)
 '(neo-window-width 50)
 '(neo-vc-integration (quote (face)))
 '(neo-cwd-line-style 'text)
 '(neo-window-position 'left))

(add-hook 'neotree-mode-hook
          (lambda ()
            (define-key evil-normal-state-local-map (kbd "TAB") 'neotree-enter)
            (define-key evil-normal-state-local-map (kbd "RET") 'neotree-enter)
            (define-key evil-normal-state-local-map (kbd "-") 'neotree-enter-horizontal-split)
            (define-key evil-normal-state-local-map (kbd "/") 'neotree-enter-vertical-split)
            (define-key evil-normal-state-local-map (kbd "s") 'neotree-quick-look)
            (define-key evil-normal-state-local-map (kbd "q") 'neotree-hide)
            (define-key evil-normal-state-local-map (kbd "g") 'neotree-refresh)
            (define-key evil-normal-state-local-map (kbd "c") 'neotree-copy-node)
            (define-key evil-normal-state-local-map (kbd "n") 'neotree-create-node)
            (define-key evil-normal-state-local-map (kbd "r") 'neotree-rename-node)
            (define-key evil-normal-state-local-map (kbd "A") 'neotree-stretch-toggle)
            (define-key evil-normal-state-local-map (kbd "H") 'neotree-hidden-file-toggle)))
