theme = "custom"

[editor]
line-number = "relative"
mouse = true
cursorline = true
rulers = []

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "file-name"]
center = []
right = ["diagnostics", "file-encoding", "position", "file-type"]
separator = "│"

[editor.indent-guides]
render = false
character = "|"

[editor.whitespace]
render = "none"

[keys.normal]
Q = ":q"
K = "hover"
G = "goto_last_line"
