shell:
  program: wsl ~

font:
  size: 11
  normal:
    family: "FuraMono NF"
    style: "Regular"
  bold:
    family: "FuraMono NF"
    style: "Medium"

import: 
  - C:\Users\theon\AppData\Roaming\alacritty\themes\tokyonight.yml
