require("plugins")
require("defauts")
require("keymaps")
require("editing")
require("lsp")
require("ui")

-- plugin config
require("plugins/lualine")
require("plugins/fzf")
require("plugins/gitsigns")
require("plugins/toggleterm")
require("plugins/indent_blankline")
require("plugins/autopairs")
-- require("plugins/bufferline")
