#!/bin/sh

## RESET

bspc rule -r "*"

## AUTOSTART
## Note: make sure a single instance of these will
## run after multiple restarts

/home/theocodes/.dotfiles/bin/launchpolybar &
/home/theocodes/.dotfiles/bin/fixmonitors &
nitrogen --restore
nm-applet &
picom &

## CONFIG

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            12
bspc config focus_follows_pointer true
bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true

## RULES

bspc rule -a Emacs state=tiled
