#!/bin/sh

# update and install base dependencies
sudo apt update -y && sudo apt install -y fish stow

# use fish as default
chsh -s /usr/bin/fish

if ! test -f "$HOME/.nix-profile/bin/nix"; then
	curl -L https://nixos.org/nix/install | sh
	. /home/$USER/.nix-profile/etc/profile.d/nix.sh
	
	nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
	nix-channel --update
fi
