#!/bin/sh

set -e

sync () {
    echo -e "\n==== Pushing changes ====\n"
    git add .
    git commit -m "$(date)"
    git push -u origin master
    echo
}

if [[ "$1" = "sync" ]]; then
    sync
else
    pushd ~/dotfiles
    make $1
    sync
    popd
fi
