#!/bin/sh

cmd=$1

if [[ $cmd = "ip" ]]; then
    ip="$(curl -s canhazip.com)"
    if [ $? -eq 0 ]; then
	echo $ip
    else
	echo "offline"
    fi
fi

if [[ $cmd = "volume" ]]; then
    muted=$(pamixer --get-mute)
    if [ $muted = "false" ]; then
	pamixer --get-volume
	exit 0
    fi

    echo "muted"
fi
