#!/bin/sh

# command="dmenu $@"
command="rofi -i -dmenu"

power_off="Shutdown"
reboot="Reboot"
lock="Lock"
suspend="Sleep"
log_out="Logout"

options="$lock\n$reboot\n$power_off\n$suspend\n$log_out"

res="$(echo -e "$options" | $command)"
case "$res" in
$power_off)
	systemctl poweroff
	;;
$reboot)
	systemctl reboot
	;;
$lock)
	xlock
	;;
$suspend)
	systemctl suspend
	;;
$log_out)
	herbstclient quit
	# pkill qtile
	;;
esac
