return {
  "lewis6991/gitsigns.nvim",
  "dag/vim-fish",
  "terrortylor/nvim-comment",
  "axelf4/vim-strip-trailing-whitespace",
  "machakann/vim-highlightedyank",
  "tpope/vim-fugitive",
  "tpope/vim-rhubarb",
  "tpope/vim-eunuch",
  -- currently causing lag
  --"github/copilot.vim",
  "windwp/nvim-autopairs",
  "Mofiqul/adwaita.nvim",
  "lunarvim/horizon.nvim",
  "axelf4/vim-strip-trailing-whitespace",
  "machakann/vim-highlightedyank",
  "nvim-treesitter/nvim-treesitter",
  "mbbill/undotree",
  { "maxjacobson/vim-fzf-coauthorship", dependencies = { "junegunn/fzf" } },
}
