#!/bin/sh

# autostart stuff
/home/theocodes/dotfiles/bin/fixmonitors &
/home/theocodes/dotfiles/bin/launchpolybar &
nitrogen --restore &
nm-applet &
picom &

BackgroundColor='#282a36'
GreenColor='#50fa7b'
GrayColor='#6272a4'
blue='#6272a4'
PrimaryColor=$blue
SecondaryColor='#ff79c6'

Font='CascadiaMono:size=10'
Browser='firefox'
Editor='emacsclient -c -n'
Terminal='alacritty'
Mod=Super

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#000000'

# remove all existing keybindings
hc keyunbind --all

# settings
hc set default_frame_layout 0
hc set focus_follows_mouse true

# monitors
hc set_monitors 2000x1440+0+0 1440x1440+2000+0

# padding for polybar
hc pad 0 30 0 0 0
hc pad 1 30 0 0 0

# keybindings

# hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-q spawn /home/theocodes/dotfiles/bin/powermenu -fn $Font -nb $BackgroundColor -nf '#ffffff' -sb $PrimaryColor
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-Return spawn $Terminal
hc keybind $Mod-Shift-Return spawn $Browser
hc keybind $Mod-d spawn dmenu_run -fn $Font -nb $BackgroundColor -nf '#ffffff' -sb $PrimaryColor

hc sethc se

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma  use_index -1
hc keybind $Mod-Right use_index +1
hc keybind $Mod-Left  use_index -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# colors
hc set frame_border_active_color '#ff79c6'
hc set frame_border_normal_color '#101010'
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set window_border_width 1
hc set window_border_normal_color $BackgroundColor
hc set window_border_active_color $PrimaryColor
hc set always_show_frame 0
hc set window_gap 0
hc set frame_gap 0
hc set frame_padding 0
hc set snap_distance 2
hc set snap_gap 2

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class~'[Ww]bar' manage=off
hc rule class~'[Cc]onky' manage=off
hc rule class~'[Ff]brun' pseudotile=on
hc rule class~'[Ss]team' floating=on

# unlock, just to be sure
hc unlock
