;; Add custom modules to load path
(setq load-path (cons "~/.emacs.d/modules" load-path))

(require 't-straight)
(require 't-defaults)
(require 't-theme)
(require 't-ui)
(require 't-window-management)
(require 't-evil)
(require 't-term)
(require 't-editing)
(require 't-lsp)
(require 't-completion)
(require 't-keybindings)
(require 't-magit)
(require 't-org)
(require 't-golang)
(require 't-ruby)
